### PR TITLE
Issue in fastjet

### PR DESCRIPTION
**Pull request by yuichiok**
Hi @airqui,

About the error I messaged you, I figured out the issue was pulling the entire fastjet namespace into the global namespace.
Thus I needed to make some editing to BBbarAnalysis codes to build the processor.
Build was successful after the change but I'd like you to take a look at it if it's okay.

### CODE REVIEW

**Comment by airqui** [comment]
Hi @yuichiok 
sorry for the late reply. I am not sure if your changes will work at the end or not even though it compiles.
what it works 100% sure is to modify the CMakeLists.txt to include the references to fastjet (I am pushing these changes in a moment)

**Comment by airqui** [comment]
Hi @yuichiok wait a minute... i see now that these changes were already there... this is strange. Let me check if it compiler or not in my side.

**Comment by airqui** [comment]
Okey... I don't understand where the issue is but your changes are correct. For the coming versions we should run with gcc82 centos 7 since sl6 support will be discontinued, but let's leave this for the QQbarAnalysisBranch2021

**Comment by airqui** [comment]
Merged. I have pushed a small change in TreeStructures.hh (a typo),
to retrieve it you should pull it. @yuichiok

**Comment by yuichiok** [comment]
@airqui 
Thank you very much.
The build failed when using gcc82 centos 7.
From the error I sent,
```
/sw/ilc/ilcsoft/gcc820/v02-01-02/root/6.18.04/include/TMatrixTUtils.h: In member function ‘const Element& TMatrixTRow_const<Element>::operator()(Int_t) const’:
/sw/ilc/ilcsoft/gcc820/v02-01-02/root/6.18.04/include/TMatrixTUtils.h:143:10: error: reference to ‘Error’ is ambiguous
          Error("operator()","Request col(%d) outside matrix range of %d - %d",
          ^~~~~
In file included from /sw/ilc/ilcsoft/gcc820/FastJet/3.2.1/include/fastjet/PseudoJet.hh:43,
                 from /home/ilc/yokugawa/QQbarAnalysis/./include/BBbarAnalysis.hh:31,
                 from /home/ilc/yokugawa/QQbarAnalysis/./include/QQbarProcessor.hh:27,
                 from /home/ilc/yokugawa/QQbarAnalysis/src/QQbarProcessor.cc:1:
/sw/ilc/ilcsoft/gcc820/FastJet/3.2.1/include/fastjet/Error.hh:47:7: note: candidates are: ‘class fastjet::Error’
 class Error {
       ^~~~~
In file included from /sw/ilc/ilcsoft/gcc820/v02-01-02/root/6.18.04/include/TMath.h:18,
                 from /home/ilc/yokugawa/QQbarAnalysis/./include/BBbarAnalysis.hh:26,
                 from /home/ilc/yokugawa/QQbarAnalysis/./include/QQbarProcessor.hh:27,
                 from /home/ilc/yokugawa/QQbarAnalysis/src/QQbarProcessor.cc:1:
/sw/ilc/ilcsoft/gcc820/v02-01-02/root/6.18.04/include/TError.h:68:13: note:                 ‘void Error(const char*, const char*, ...)’
 extern void Error(const char *location, const char *msgfmt, ...)
             ^~~~~
```
it seems that the error comes from the fact that both `ROOT` and `fastjet` has function called `Error` which is interfering each other when fastjet namespace has been declared.
Anyway, I'm glad it's solved!

**Pull request merged**
